name: ci
on:
  pull_request:
    paths-ignore:
      - "**.md"

env:
  TERRAFORM_VERSION: 1.12.1
jobs:
  validate-versions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          # Each directory in folder is a module
          - "fides-aws-ecs"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Required to get full history for comparing versions
          fetch-depth: 0

      - name: Extract version from version.json
        id: extract-version
        run: |
          VERSION_FILE="${{ matrix.module }}/version.json"
          MODULE=$(jq --raw-output '.module' "$VERSION_FILE")
          VERSION=$(jq --raw-output '.version' "$VERSION_FILE")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Validate semantic version
        uses: matt-usurp/validate-semver@v2
        with:
          version: ${{ steps.extract-version.outputs.version }}

  check-terraform-formatting:
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        id: tf-setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - name: Check Terraform Formatting
        id: tf-fmt
        run: terraform fmt -check -recursive -no-color
