name: ci
on:
  pull_request:
    paths-ignore:
      - "**.md"
jobs:
  validate-versions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          # Each directory in folder is a module
          - "fides-aws-ecs"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required to get full history for comparing versions

      # Extract version from version.json
      - name: Extract version from version.json
        id: extract-version
        run: |
          VERSION_FILE="${{ matrix.module }}/version.json"
          MODULE=$(jq -r '.module' "$VERSION_FILE")
          VERSION=$(jq -r '.version' "$VERSION_FILE")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # Validate semantic version using a pre-built action
      - name: Validate semantic version
        uses: matt-usurp/validate-semver@v2
        with:
          version: ${{ steps.extract-version.outputs.version }}

  check-terraform-formatting:
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        id: tf-setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.4
      - name: Check Terraform Formatting
        id: tf-fmt
        run: terraform fmt -check -recursive -no-color
