name: Release Terraform Modules

on:
  push:
    branches:
      - main
    paths:
      - "*/version.json"

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10 # Prevent long-running jobs
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Needed to get all tags history

      - name: Find changed version.json files
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'version.json$' || true)
          if [ -z "$CHANGED_FILES" ]; then
            echo "No version.json files changed"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changed version files: $CHANGED_FILES"
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "changed_files<<EOF" >> $GITHUB_OUTPUT
            echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi

      - name: Tag modules with updated versions
        id: tagging
        if: steps.changed-files.outputs.has_changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          # Initialize empty arrays for created tags
          CREATED_TAGS=()

          # Process each changed version.json file
          for VERSION_FILE in ${{ steps.changed-files.outputs.changed_files }}; do
            # Get the module directory from the path
            MODULE_DIR=$(dirname "$VERSION_FILE")
            
            # Parse the version.json file
            if [ ! -f "$VERSION_FILE" ]; then
              echo "Warning: $VERSION_FILE no longer exists, skipping"
              continue
            fi
            
            # Validate JSON
            if ! jq empty "$VERSION_FILE" 2>/dev/null; then
              echo "Error: $VERSION_FILE is not valid JSON, skipping"
              continue
            fi
            
            MODULE=$(jq -r '.module' "$VERSION_FILE")
            VERSION=$(jq -r '.version' "$VERSION_FILE")
            
            # Validate required fields
            if [ "$MODULE" = "null" ] || [ -z "$MODULE" ] || [ "$VERSION" = "null" ] || [ -z "$VERSION" ]; then
              echo "Error: $VERSION_FILE is missing required module or version fields, skipping"
              continue
            fi
            
            echo "Processing module: $MODULE (directory: $MODULE_DIR) with version: $VERSION"
            
            # Check if this tag already exists
            TAG_NAME="${MODULE}/v${VERSION}"
            if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
              echo "Tag $TAG_NAME already exists, skipping"
              continue
            fi
            
            # Create and push tag
            echo "Creating tag: $TAG_NAME"
            if git tag -a "$TAG_NAME" -m "Release $MODULE version $VERSION" && git push origin "$TAG_NAME"; then
              echo "Tagged $MODULE with version $VERSION"
              CREATED_TAGS+=("$TAG_NAME")
            else
              echo "Error creating or pushing tag $TAG_NAME"
            fi
          done

          # Convert array to JSON and set outputs
          if [ ${#CREATED_TAGS[@]} -gt 0 ]; then
            CREATED_TAGS_JSON=$(printf '%s\n' "${CREATED_TAGS[@]}" | jq -R . | jq -s .)
            echo "tags_created=true" >> $GITHUB_OUTPUT
            echo "created_tags_json=$CREATED_TAGS_JSON" >> $GITHUB_OUTPUT
            echo "Successfully created ${#CREATED_TAGS[@]} tag(s)"
          else
            echo "tags_created=false" >> $GITHUB_OUTPUT
            echo "created_tags_json=[]" >> $GITHUB_OUTPUT
            echo "No new tags were created"
          fi

      - name: Create summary
        if: always()
        run: |
          echo "### Release Summary" >> $GITHUB_STEP_SUMMARY
          echo "* Tags created: ${#CREATED_TAGS[@]}" >> $GITHUB_STEP_SUMMARY
          if [ ${#CREATED_TAGS[@]} -gt 0 ]; then
            echo "* Created tags:" >> $GITHUB_STEP_SUMMARY
            for TAG in "${CREATED_TAGS[@]}"; do
              echo "  - $TAG" >> $GITHUB_STEP_SUMMARY
            done
          fi

      - name: Repository Dispatch
        # This gets used to update the documentation.
        if: steps.tagging.outputs.tags_created == 'true'
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: terraform-released
          client-payload: '{"tags": ${{ steps.tagging.outputs.created_tags_json }}, "ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
